name: Build and deploy to OpenShift

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "kilo-dev"
  APP_NAME: "my-go-app"
  APP_PORT: "8084"
  IMAGE_REGISTRY: docker.io/mridul017
  IMAGE_REGISTRY_USER: mridul017
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
  IMAGE_TAGS: ""

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  openshift-ci-cd:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-20.04
    environment: production

    steps:
    - name: Check for required secrets
      uses: actions/github-script@v6
      with:
        script: |
          const secrets = {
            OPENSHIFT_SERVER: process.env.OPENSHIFT_SERVER,
            OPENSHIFT_TOKEN: process.env.OPENSHIFT_TOKEN,
          };

          const GHCR = "ghcr.io";
          if (process.env.IMAGE_REGISTRY.startsWith(GHCR)) {
            core.info(`Image registry is ${GHCR} - no registry password required`);
          } else {
            core.info("A registry password is required");
            secrets["IMAGE_REGISTRY_PASSWORD"] = process.env.IMAGE_REGISTRY_PASSWORD;
          }

          const missingSecrets = Object.entries(secrets).filter(([name, value]) => {
            if (!value) {
              core.error(`Secret "${name}" is not set`);
              return true;
            }
            core.info(`✔️ Secret "${name}" is set`);
            return false;
          });

          if (missingSecrets.length > 0) {
            core.setFailed(`❌ At least one required secret is not set in the repository.`);
          } else {
            core.info(`✅ All the required secrets are set`);
